package com.Model.Enum;

public enum Clas_trabajo {
    FUERZAS_MILITARES,
    DIRECTORES_GERENTES,
    PROFESIONALES_CIENTIFICOS,
    TECNICOS_PROFESIONALES,
    PERSONAL_APOYO_ADM,
    TRABAJADORES_VENDEDORES
}
